all: function
# input_name parameters function

input_name: input_name.c
	gcc -g -Wall input_name.c
parameters: parameters.c
	gcc -g -Wall parameters.c
function: function.c
	gcc -g -Wall function.c


