all: pipe_ls_wc
# sigusr1_intro sigsegv sig_child wait_3_seconds infinite_alarm pipe_ls_wc
sigusr1_intro: sigusr1_intro.c
	gcc -g -Wall sigusr1_intro.c
sigsegv: sigsegv.c
	gcc -g -Wall sigsegv.c
sig_child: sig_child.c
	gcc -g -Wall sig_child.c
wait_3_seconds: wait_3_seconds.c
	gcc -g -Wall wait_3_seconds.c
infinite_alarm: infinite_alarm.c
	gcc -g -Wall infinite_alarm.c
pipe_ls_wc: pipe_ls_wc.c
	gcc -g -Wall pipe_ls_wc.c